services:
  postgres:
    image: postgres:latest
    restart: always
    platform: linux/arm64 
    env_file:
      - '.env'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mg_symposium_bot
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: make start
    env_file:
      - '.env'

volumes:
  postgres_data: