services:
  postgres:
    image: postgres:latest
    restart: always
    platform: linux/arm64 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mg_symposium_bot
    platform: linux/arm64 
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: make start
    env_file:
      - '.env.docker'

volumes:
  postgres_data: