services:
  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  mgsu_bot:
    image: sanichmyshkin/symposium:latest
    container_name: symposium
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-container
    command: make start


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  postgres-data: