"""Initial migration

Revision ID: e892e0be3afc
Revises: 42f3b1c974d7
Create Date: 2024-09-14 10:46:13.850965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e892e0be3afc'
down_revision: Union[str, None] = '42f3b1c974d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
